[IMPROVEMENT] - New pattern and ESlint implementation
betrybe/sd-0x-project-starwars-planets-search pull request #7
Opened 2020-11-03 12:10 UTC by LizzardMedeiros

2020-11-03 12:41 UTC, albertosca requested changes
Alguns pontos:
1. Faz um sumário, tipo [esse](https://github.com/betrybe/sd-0x-project-trivia-react-redux#sum%C3%A1rio), pra nós nesse README? Acho que ficaria bem legal!
2. A seção `Copiando os arquivos entre projetos` tem que desaparecer. Concorda?
3. Muda o nome do projeto e do repo? Pra `starwars-planets-search-engine`. Acho que é melhor!
4. Tem que mudar o .yml pro avaliador funcionar! Dá uma olhada no avaliador do projeto 16, Trybewallet, que é na mesma linha.

2020-11-03 12:41 UTC, albertosca commented on .eslintignore
> +src/App.test.js
```suggestion
src/App.test.js

```

2020-11-03 12:41 UTC, albertosca commented on package.json
> +    "eslint": "^6.8.0",
```suggestion
    "eslint": "6.8.0",
```

2020-11-03 12:41 UTC, albertosca commented on .trybe/requirements.json
> +    "description": "Apague e desfaça as filtragens dos dados da tabela ao clicar no ícone de `X`",
```suggestion
    "description": "Apague o filtro de valores numéricos e desfaça as filtragens dos dados da tabela ao clicar no ícone de `X` de um dos filtro",
```

2020-11-03 12:41 UTC, albertosca commented on src/App.test.js
> +describe('Apague e desfaça as filtragens dos dados da tabela ao clicar no ícone de `X`', () => {
```suggestion
describe('Apague o filtro de valores numéricos e desfaça as filtragens dos dados da tabela ao clicar no ícone de `X` de um dos filtro', () => {
```

2020-11-03 12:41 UTC, albertosca commented on README.md
> +- A tabela deve ter 11 linhas
```suggestion
- A tabela deve ter uma linha para cada planeta retornado
```

Vale mudar no teste também! Rola de mudar lá?

2020-11-03 12:41 UTC, albertosca commented on README.md
> +### Crie um filtro para valores numéricos
```suggestion
### 3 - Crie um filtro para valores numéricos
```

2020-11-03 12:48 UTC, LizzardMedeiros commented on .eslintignore
> +src/App.test.js
Pq vc quer manter o App.test na avaliação do eslint?

2020-11-03 12:56 UTC, albertosca commented on .eslintignore
> +src/App.test.js
Eu não mudei isso! Só coloquei uma quebra de linha no final do arquivo, pra manter o padrão :D

2020-11-03 13:58 UTC, LizzardMedeiros commented on .eslintignore
> +src/App.test.js
Ah, vdd! KKKKKKKKKKKKKKKKKKK

2020-11-03 13:59 UTC, LizzardMedeiros commented
@albertosca, eu tive problemas para acrescentar os steps dos requerimentos no sumário, então vou subir sem ele por enquanto, não quero perder tempo com isso agora, preciso terminar o projeto do bloco 11, blz? Depois disso, volto nesse README e deixo lindão pra vc S2

2020-11-09 20:55 UTC, albertosca requested changes

2020-11-09 20:55 UTC, albertosca commented on .github/workflows/main.yml
> +        uses: betrybe/react-scripts-evaluator-action@v4
Tem que mudar esse arquivo (com a `eslint-linter-action` na `v2.1`)!

2020-11-09 20:55 UTC, albertosca commented on README.md
> +  - Utilizar o useEffect para gerenciar os ciclos de vida dos componentes funcionais
```suggestion
Nesse projeto, você será capaz de:

* Utilizar a _Context API_ do **React** para gerenciar estado.

* Utilizar o _React Hook useState_;

* Utilizar o _React Hook useContext_;

* Utilizar o _React Hook useEffect_

* Criar _React Hooks_ customizados
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Habilidades
```suggestion
## HABILIDADES
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Sumário
```suggestion
## SUMÁRIO
```

E tem mudar aqui tudo que mudar nas outras seções depois!

2020-11-09 20:55 UTC, albertosca commented on README.md
> +- [Lista de requisitos](#lista-de-requisitos)
Vale listar todos os requisitos!

2020-11-09 20:55 UTC, albertosca commented on README.md
>  ## Instruções para entregar seu projeto:
```suggestion
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +### Antes de começar a desenvolver:
```suggestion
## COMO DESENVOLVER
### Antes de começar a desenvolver
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +O projeto deverá ser entregue até a seguinte data para a avaliação final: ``DD/MM/YYYY - 00:00h``.
```suggestion
## DATA DE ENTREGA
* Projeto em grupo.

* Serão cinco dias de projeto.

* O projeto tem até a seguinte data: dd/mm/yyyy - 14:00h para ter entregue a avaliação final.
```

Jogar essa seção lá pra cima, logo abaixo da `O QUE DEVERÁ SER DESENVOLVIDO`

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Como desenvolver
```suggestion
## COMO DESENVOLVER
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +Você vai desenvolver uma lista com filtros de planetas do universo de StarWars usando **Context API e Hooks** para controlar os estados globais.
Essa seção precisa ter título em caixa alta e precisa ir logo abaixo do sumário! Além disso, acho que rolava de explicar um tiquitin mais o que seria o projeto e colocar um gifzinho dele funcionando! Que que vc acha?

2020-11-09 20:55 UTC, albertosca commented on README.md
>  ## Requisitos do projeto
```suggestion
## REQUISITOS DO PROJETO
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +
Onde no projeto a gente tá falando da API, explicando entrada e saída dos endpoints, dando uns exemplos e links? 🤔 

Vale ter essa seção aqui, esteja ela já pronta ou caso tenhamos que fazer!

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Lista de requisitos
```suggestion
## LISTA DE REQUISITOS
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +O que será verificado:
Importante, _em cada requisito_, ter uma seção `Observações técnicas` com tudo que é necessário ter no código pro avaliador aprovar!

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Durante o desenvolvimento
```suggestion
## DURANTE O DESENVOLVIMENTO
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Depois de terminar o desenvolvimento (opcional)
```suggestion
## DEPOIS DE TERMINAR O DESENVOLVIMENTO (OPCIONAL)
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +
✂️ Atenção! 😬 
Essa seção ficou duplicada.

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Revisando um Pull Request
```suggestion
## REVISANDO UM PULL REQUEST
```

2020-11-09 20:55 UTC, albertosca commented on README.md
>  #VQV 🚀
```suggestion
```

2020-11-09 20:55 UTC, albertosca commented on README.md
> +## Avisos Finais
```suggestion
# AVISOS FINAIS
```

2020-11-09 20:55 UTC, albertosca commented on src/App.test.js
> +  it('a tabela deve ter 13 colunas', async () => {
```suggestion
  it('A tabela deve ter 13 colunas', async () => {
```

Vale revisar _todos_ os its e as respectivas representações no README pra garantir que todos começam bonitinho com caixa alta!

2020-11-09 20:56 UTC, albertosca commented
Falta mudar o nome do projeto e dos repos também! =)

2020-11-17 12:49 UTC, icaroharry approved these changes

2020-11-17 12:50 UTC, merged