[Improvement] - README and linter
betrybe/sd-0x-project-starwars-planets-search pull request #9
Opened 2020-12-07 15:13 UTC by LizzardMedeiros

2020-12-08 20:28 UTC, albertosca reviewed
@StoneHg @icaroharry Vcs tem alguma sugestão de mudança que poderia rolar no README/requisitos desse projeto?

A propósito, @LizzardMedeiros eu proponho juntar as mudanças do #10 a esse PR, dá uma olhada lá! Se vc aprovar a sugestão eu mesmo jogo o código novo aqui.

2020-12-08 20:28 UTC, albertosca commented on .stylelintrc.json
> +	],
Tem que corrigir esse espaçamento!

2020-12-08 20:28 UTC, albertosca commented on README.md
> +## Linter
Vale acrescentar nessa seção que usamos o stylelint também.

2020-12-08 20:28 UTC, albertosca commented on .eslintrc.json
> +  "extends": ["plugin:react/recommended", "airbnb", "eslint:recommended"],
Porque mesmo precisamos desse `eslint:recommended`?
As regras de hooks tão inclusas?

2020-12-08 20:28 UTC, albertosca commented on .eslintrc.json
> +
```suggestion

```
✂️ nessa linha em branco

2020-12-08 20:28 UTC, albertosca commented on README.md
> +Você vai desenvolver uma lista com filtros de planetas do universo de StarWars usando **Context API e Hooks** para controlar os estados globais.
```suggestion
Você vai desenvolver uma lista com filtros de planetas do universo de Star Wars usando **Context API e Hooks** para controlar os estados globais.
```

2020-12-08 20:35 UTC, LizzardMedeiros commented on .eslintrc.json
> +  "extends": ["plugin:react/recommended", "airbnb", "eslint:recommended"],
Sugestão para o eslint-plugin-react, vou aprofundar pra saber o que ele faz

2020-12-08 20:36 UTC, LizzardMedeiros commented on README.md
> +## Linter
Boa

2020-12-10 16:30 UTC, LucasCFerraz commented on README.md
> +Para garantir a qualidade do seu código de forma a tê-lo mais legível, de mais fácil manutenção e seguindo as boas práticas de desenvolvimento nós utilizamos neste projeto o linter `ESLint` e o `Styl
Aqui faltou um npm run lint:styles não?

2020-12-10 20:19 UTC, antoniosb commented on .editorconfig
> +[*.{js,html,md,css}]
faz sentido incluir `jsx` ?

2020-12-11 12:29 UTC, LizzardMedeiros commented on README.md
> +Para garantir a qualidade do seu código de forma a tê-lo mais legível, de mais fácil manutenção e seguindo as boas práticas de desenvolvimento nós utilizamos neste projeto o linter `ESLint` e o `Styl
@LucasCFerraz, pronto. Inseri o script e o comando no README =)

2021-01-04 19:05 UTC, albertosca commented on .editorconfig
> +[*.{js,html,md,css}]
```suggestion
[*.{js,jsx,html,md,css}]
```

2021-01-04 19:06 UTC, albertosca commented on .editorconfig
> +[*.{js,html,md,css}]
@antoniosb Done! Dá uma olhadinha.

2021-01-04 19:36 UTC, StoneHg approved these changes

2021-01-05 01:20 UTC, pauloricardoz commented on README.md
> +Este repositório já contém um _template_ de uma aplicação React criado e configurado. Após clonar o projeto e instalar as dependências (mais sobre isso abaixo), você **poderá** copiar os arquivos que
Acho que essa parte ficou fora de contexto agora, pois o projeto anterior não é mais o StarWars com Redux.

2021-01-05 01:21 UTC, pauloricardoz commented on README.md
> +Caso não tenha realizado o projeto anterior, você deverá implementar todos os requisitos obrigatórios do projeto anterior e os novos requisitos do projeto atual. Contudo, não é necessário primeiro de
Se o comentário anterior for valido, o mesmo vale para esse ponto.

2021-01-05 01:23 UTC, pauloricardoz requested changes
Se for valido olhar o ponto que se refere ao projeto anterior (StarWar com Redux).

2021-01-05 11:17 UTC, LizzardMedeiros commented on README.md
> +Este repositório já contém um _template_ de uma aplicação React criado e configurado. Após clonar o projeto e instalar as dependências (mais sobre isso abaixo), você **poderá** copiar os arquivos que
Boa, PR!

2021-01-05 12:15 UTC, pauloricardoz approved these changes

2021-01-05 12:52 UTC, jeanpsv approved these changes

2021-01-05 14:08 UTC, phelipe-ohlsen approved these changes

2021-01-20 18:57 UTC, albertosca requested changes
Bora numerar os requisitos! No `.trybe/requirements.json`, nos testes, no repo `-tests`. Aí a gente retesta e mergeia! Rola?

2021-02-03 13:02 UTC, albertosca approved these changes
Importante testar em staging outra vez depois de mergearmos!

2021-02-03 13:52 UTC, merged

2021-02-03 16:32 UTC, pauloricardoz commented on README.md
> +### 3 - Crie um filtro para valores numéricos
Esse ponto dentro desse tópico tem confundido alguns estudantes
[linha 201 ou 210] 
`filters { filterByName: { name }, filterByNumericValues: [{ column, comparison, value }] }`
Alguns tem achado que são obrigados a colocar um objeto inicialmente dentro do filterByNumericValues

2021-02-03 16:32 UTC, pauloricardoz commented on README.md
>  Caso um filtro seja totalmente preenchido, um novo filtro de valores numéricos deve ser carregado. Este novo filtro não deve incluir quaisquer colunas que já tenham sido selecionadas em filtros de va
Seria interessante trocar o termo carregado por aplicado.
"Caso um filtro seja totalmente preenchido, um novo filtro de valores numéricos deve ser aplicado a lista de planetas. Este novo filtro não deve incluir quaisquer colunas que já tenham sido selecionadas em filtros de valores numéricos anteriores. Caso todas as colunas já tenham sido inclusas em filtros anteriores, **o select das colunas deve ficar vazio** .Você deve usar **Context API e Hooks** para fazer o gerenciamento do estado da aplicação."

2021-02-03 16:32 UTC, pauloricardoz commented on README.md
> +### Bônus
[linha 308 317] o test realiza a checagem do **orbital_period**, e não do **population**, pelo menos era assim até a turma 7. Então seria interessante trocar isso no readme e na descrição do teste

2021-02-03 16:32 UTC, pauloricardoz commented on src/App.test.js
> +  it('Ordene os planetas do mais populoso para o menos populoso', async () => {
A ordenação  teste é feita pelo [orbital_period](url)